# Generated by Django 4.2.2 on 2023-06-14 10:17

from django.db import migrations, models
import users.models.file


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_portfolio_is_published_alter_portfolio_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliofile",
            name="image",
            field=models.ImageField(
                max_length=255, upload_to=users.models.file._upload_to
            ),
        ),
    ]
