# Generated by Django 4.2.2 on 2023-06-14 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_portfolio_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement",
                    models.CharField(
                        choices=[
                            ("CREATED_PAGE", "Created Page"),
                            ("FIRST_PROJECT", "First Project"),
                            ("FIFTY_LIKES", "Fifty Likes"),
                            ("TEN_LIKES", "Ten Likes"),
                            ("FIRST_COMMENT", "First Comment"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
