# Generated by Django 4.2.2 on 2023-06-14 16:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_achievement_mark_as_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
            ],
        ),
    ]
